config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  root to: 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :events
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :find_event, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@events = Event.all.order("calendar_entry DESC")
	end

	def show
		@events = Event.where(event_id: @event)

	end

	def new
		@event = current_user.events.build
	end

	def create
		@event = current_user.events.build(event_params)

		if @event.save
			redirect_to @event
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @event.update(event_params)
			redirect_to @event
		else
			render 'edit'
		end
	end

	def destroy
		@event.destroy
		redirect_to root_path
	end

	private

	def find_event
		@event = Event.find(params[:id])
	end

	def event_params
		params.require(:event).permit(:title, :description, :calendar_entry, :image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= simple_form_for @event do |f|
	= f.input :title
	= f.input :description
	= f.input :calendar_entry
	= f.input :image

	= f.button :submit

app/views/events/edit.html.haml
%h1 Edit an event

= render 'form'

app/views/events/index.html.haml
- if user_signed_in?
	%p
		Hello
		= current_user.username
		%br/
		%span
			Get excited by the future!
- else
	%p
		What are you excited about?
		%br/
		%span
			Get excited by the future!
- @events.each do |event|
	%h2= link_to event.title, event
	- if (event.calendar_entry - Date.today).to_i > 0
		= (event.calendar_entry - Date.today).to_i
		days left
	- else
		This event has passed!
	%p
		Shared by
		= event.user.username

app/views/events/new.html.haml
%h1 Add an event

= render 'form'

app/views/events/show.html.haml
%h1= @event.title
%p
	Shared by
	= @event.user.username
	= time_ago_in_words(@event.created_at)
	ago
	.description= simple_format(@event.description)
	- if (@event.calendar_entry - Date.today).to_i > 0
		= (@event.calendar_entry - Date.today).to_i
		days left
	- else
		This event has passed!
	= image_tag @event.image.url(:medium)
	- if @event.user == current_user
		= link_to "Edit", edit_event_path(@event), class: "data"
		= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure?" }, class: "data"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Countdown Timer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= html_import_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<paper-header-panel>
	<paper-toolbar>
		<div>Countdown Timer</div>
		<div>Sign In/Sign Up</div>
	</paper-toolbar>
  	<div>
  		<%= yield %>
  	</div>
</paper-header-panel>

<paper-button raised>New workout</paper-button>
<paper-fab id="add" icon="add" role="button" tabindex="0" aria-disabled="false" class="x-scope paper-fab-0"></paper-fab>

</body>
</html>